apps/accounts/urls.py
from django.urls import path

from apps.accounts.views import user_account, user_login, user_register, user_reset_password

app_name = 'accounts'

urlpatterns = [
    path('user-reset-password/', user_reset_password, name='reset-password'),
    path('user-register/', user_register, name='register'),
    path('user-login/', user_login, name='login'),
    path('', user_account, name='account')
]

apps/blogs/urls.py
from django.urls import path

from apps.blogs.views import blogs_list_view, blogs_detail_view

app_name = 'blogs'

urlpatterns = [
    path('<int:pk>/', blogs_detail_view, name='detail'),
    path('', blogs_list_view, name='list')
]

apps/pages/urls.py
from django.urls import path

from apps.pages.views import home_page_view, contact_page_view, n404_page_view, about_us_page_view, user_wishlist_page_view

app_name = 'pages'

urlpatterns = [
    path('user-wishlist/', user_wishlist_page_view, name='user-wishlist'),
    path('about-us/', about_us_page_view, name='about-us'),
    path('404/', n404_page_view, name='404'),
    path('contact/', contact_page_view, name='contact'),
    path('', home_page_view, name='home')
]

apps/products/urls.py
from django.urls import path

from apps.products.views import products_page_view, product_checkout_page_view, product_detail_page_view, product_grid_page_view

app_name = 'products'

urlpatterns = [
    path('product-grid-sidebar-left/', product_grid_page_view, name='grid'),
    path('product-detail/', product_detail_page_view, name='detail'),
    path('product-checkout/', product_checkout_page_view, name='checkout'),
    path('', products_page_view, name='cart')
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('apps.products.urls', namespace='products')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('', include('apps.pages.urls', namespace='pages')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/blogs/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UserModel(BaseModel):
    full_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='users/')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'


class ProfileModel(BaseModel):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)


class CategoryModel(BaseModel):
    title = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class TagModel(BaseModel):
    title = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class PostModel(BaseModel):
    image = models.ImageField(upload_to='posts/')
    title = models.CharField(max_length=255)

    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    tags = models.ManyToManyField(
        TagModel,
        related_name='posts'
    )

apps/pages/models.py
from django.db import models


class ContactModel(models.Model):
    full_name = models.CharField(max_length=128)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()

    is_read = models.BooleanField(default=False)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.full_name} => {self.email}"

    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

apps/products/models.py
from django.db import models

# Create your models here.

apps/pages/forms.py
from django import forms

from apps.pages.models import ContactModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        exclude = ['is_read', 'comment']


    def clean(self):
        print("Object level validation")
        print(self.cleaned_data)
        return super().clean()

apps/accounts/views.py
from django.shortcuts import render

def user_account(request):
    return render(request, 'accounts/user-account.html')

def user_login(request):
    return render(request, 'accounts/user-login.html')

def user_register(request):
    return render(request, 'accounts/user-register.html')

def user_reset_password(request):
    return render(request, 'accounts/user-reset-password.html')

apps/blogs/views.py
from django.shortcuts import render

from apps.blogs.models import PostModel, CategoryModel, TagModel


def blogs_list_view(request):
    posts = PostModel.objects.all()
    categories = CategoryModel.objects.all()
    tags = TagModel.objects.all()

    context = {
        'posts': posts,
        'categories': categories,
        'tags': tags
    }
    return render(request, 'blogs/blog-list-sidebar-left.html', context)

def blogs_detail_view(request, pk):
    try:
        post = PostModel.objects.get(id=pk)
    except PostModel.DoesNotExist:
        return render(request, 'pages/404.html')
    categories = CategoryModel.objects.all()
    tags = TagModel.objects.all()

    context = {
        'posts': post,
        'categories': categories,
        'tags': tags
    }
    return render(request, 'blogs/blog-detail.html', context)

apps/pages/views.py
from django.shortcuts import render, redirect

from apps.pages.forms import ContactForm


def home_page_view(request):
    return render(request, 'home3.html')

def contact_page_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pages:contact')
        else:
            errors = []
            for key, value in form.errors.items():
                for error in value:
                    errors.append(error)
            context = {
                "errors": errors
            }
            return render(request, 'pages/contact.html', context)

    else:
        return render(request, 'pages/contact.html')

def n404_page_view(request):
    return render(request, 'pages/404.html')

def about_us_page_view(request):
    return render(request, 'pages/about-us.html')

def user_wishlist_page_view(request):
    return render(request, 'pages/user-wishlist.html')

apps/products/views.py
from django.shortcuts import render

def products_page_view(request):
    return render(request, 'product/product-cart.html')

def product_checkout_page_view(request):
    return render(request, 'product/product-checkout.html')

def product_detail_page_view(request):
    return render(request, 'product/product-detail.html')

def product_grid_page_view(request):
    return render(request, 'product/product-grid-sidebar-left.html')

templates/accounts/user-account.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}User account{% endblock %}
{% block body-params %}class="user-acount"{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>My Account</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

            <div class="acount head-acount">
                <div class="container">
                    <div id="main">
                        <h1 class="title-page">My Account</h1>
                        <div class="content" id="block-history">
                            <table class="std table">
                                <tbody>
                                    <tr>
                                        <th class="first_item">My Name :</th>
                                        <td>David James</td>
                                    </tr>
                                    <tr>
                                        <th class="first_item">Company :</th>
                                        <td>TivaTheme</td>
                                    </tr>
                                    <tr>
                                        <th class="first_item">Address :</th>
                                        <td>123 canberra Street, New York, USA</td>
                                    </tr>
                                    <tr>
                                        <th class="first_item">City :</th>
                                        <td>New York</td>
                                    </tr>
                                    <tr>
                                        <th class="first_item">Postal/Zip Code :</th>
                                        <td>10001</td>
                                    </tr>
                                    <tr>
                                        <th class="first_item">Phone :</th>
                                        <td>0123456789</td>
                                    </tr>
                                    <tr>
                                        <th class="first_item">Country:</th>
                                        <td>USA</td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                        <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                            view Address
                        </button>
                        <div class="order">
                            <h4>Order
                                <span class="detail">History</span>
                            </h4>
                            <p>You haven't placed any orders yet.</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/user-login.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}User login{% endblock %}
{% block body-params %}class="user-login blog"{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Login</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div id="content-wrapper" class="full-width">
                <div id="main">
                    <div class="container">
                        <h1 class="text-center title-page">Log In</h1>
                        <div class="login-form">
                            <form id="customer-form" action="#" method="post">
                                <div>
                                    <input type="hidden" name="back" value="my-account">
                                    <div class="form-group no-gutters">
                                        <input class="form-control" name="email" type="email" placeholder=" Email">
                                    </div>
                                    <div class="form-group no-gutters">
                                        <div class="input-group js-parent-focus">
                                            <input class="form-control js-child-focus js-visible-password" name="password" type="password" value="" placeholder="Password">
                                        </div>
                                    </div>
                                    <div class="no-gutters text-center">
                                        <div class="forgot-password">
                                            <a href="user-reset-password.html" rel="nofollow">
                                                Forgot your password?
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix">
                                    <div class="text-center no-gutters">
                                        <input type="hidden" name="submitLogin" value="1">
                                        <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                                            Sign in
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/user-register.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}User register{% endblock %}
{% block body-params %}class="user-register blog"{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>About us</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <div id="main">
                            <div id="content" class="page-content">
                                <div class="register-form text-center">
                                    <h1 class="text-center title-page">Create Account</h1>
                                    <form action="#" id="customer-form" class="js-customer-form" method="post">
                                        <div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="firstname" type="text" placeholder="First name">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="lastname" type="text" placeholder="Last name">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="email" type="email" placeholder="Email">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <div class="input-group js-parent-focus">
                                                        <input class="form-control js-child-focus js-visible-password" name="password" type="password" placeholder="Password">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div>
                                                <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                                                    Create Account
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/user-reset-password.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}User reset password{% endblock %}
{% block body-params %}class="user-reset-password blog"{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>User Reset Password</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="onecol">
                        <div id="main">
                            <div class="page-content">
                                <form action="#" class="forgotten-password" method="post" id="customer-form">
                                    <h1 class="text-center title-page">User Reset Password</h1>
                                    <div class="form-fields text-center ">
                                        <div class="form-group center-email-fields">
                                            <div class="email">
                                                <input type="email" name="email" id="email" value="" class="form-control" placeholder="Email address">
                                            </div>
                                            <div>
                                                <button class="form-control-submit btn btn-primary" name="submit" type="submit">
                                                    Send reset link
                                                </button>
                                            </div>
                                        </div>
                                        <a href="user-login.html" class="account-link">
                                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                                            <span class="text-center">Back to login</span>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<!--<![endif]-->
<html lang="en">


<!-- blog-list-sidebar-left10:09-->
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <meta name="keywords" content="Furniture, Decor, Interior">
    <meta name="description" content="Furnitica - Minimalist Furniture HTML Template">
    <meta name="author" content="tivatheme">


    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/nivo-slider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-material/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slider-range/css/jslider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/owl-carousel/assets/owl.carousel.min.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reponsive.css' %}">
    {% block extra_css %}{% endblock %}
</head>

<body {% block body-params %}{% endblock %}>
    {% url 'pages:home' as home_url %}
    {% if request.path == home_url %}
        {% include 'layout/header-home.html' %}
    {% else %}
        {% include 'layout/header-base.html' %}
    {% endif %}

    {% block content %}{% endblock %}

    {% include 'layout/footer.html' %}

    <!-- back top top -->
    <div class="back-to-top">
        <a href="#">
            <i class="fa fa-long-arrow-up"></i>
        </a>
    </div>

    {% include 'layout/mobile-menu.html' %}

    <!-- Page Loader -->
    <div id="page-preloader">
        <div class="page-loading">
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
        </div>
    </div>

    <!-- Vendor JS -->
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/popper/popper.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'libs/nivo-slider/js/jquery.nivo.slider.js' %}"></script>
    <script src="{% static 'libs/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/tmpl.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.dependClass-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/draggable-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.slider.js' %}"></script>

    <!-- Template JS -->
    <script src="{% static 'js/theme.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>


<!-- blog-list-sidebar-left10:30-->
</html>

templates/pages/about-us.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}About us{% endblock %}
{% block body-params %}id="about-us" class="blog"{% endblock %}
{% block content %}
		<div class="main-content">
			<div id="wrapper-site">
				<div id="content-wrapper">
					
					<!-- breadcrumb -->
					<nav class="breadcrumb-bg">
						<div class="container no-index">
							<div class="breadcrumb">
								<ol>
									<li>
										<a href="#">
											<span>Home</span>
										</a>
									</li>
									<li>
										<a href="#">
											<span>About us</span>
										</a>
									</li>
								</ol>
							</div>
						</div>
					</nav>
					<div id="main">
						<div class="page-home">
							<div class="container">
								<div class="about-us-content">
									
									<h1 class="title-page">About Us</h1>
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6 right">
											<a href="#">
												<img class="img-fluid" src="{% static 'img/other/1.jpg' %}" alt="#" />
											</a>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6 left">
											<div class="cms-block f-right">
												<h3 class="page-subheading">WHO WE ARE</h3>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis biben
													dum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis
													sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
												amet nibh vultate cursus a sit amet mauris.</p>
												<p>Proin gravida nibh vel velit auctor aliquet. nec sagittis sem nibh id elit. Duis
													sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
												amet nibh vultate cursus a sit amet mauris.</p>
												<a>
													<img class="img-fluid" src="{% static 'img/other/4.png' %}" alt="#" />
													<span>Mr. kwang shang - CEO</span>
												</a>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6 right">
											<div class="cms-block f-left">
												<h3 class="page-subheading">WHAT WE DO</h3>
												<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis biben
													dum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis
													sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
												amet nibh vultate cursus a sit amet mauris.</p>
												<p>Proin gravida nibh vel velit auctor aliquet, nec sagittis sem nibh id elit. Duis
													sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
												amet nibh vultate cursus a sit amet mauris.</p>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6 left">
											<a href="#">
												<img class="img-fluid" src="{% static 'img/other/2.jpg' %}" alt="#" />
											</a>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6 right">
											<a href="#">
												<img class="img-fluid" src="{% static 'img/other/3.jpg' %}" alt="#" />
											</a>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6 left">
											<div class="cms-block f-right">
												<h3 class="page-subheading no-before">MEET OUR TEAM</h3>
												<div class="testimonials owl-carousel owl-theme owl-loaded owl-drag">
													<div class="item">
														<div class="name">William James</div>
														<div class="position">Designer - Stylish</div>
														<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
															quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
															nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
															mauris. Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
															lorem quis bibendum auctor, nisi elit conse quat ipsum
														</p>
													</div>
													<div class="item">
														<div class="name">Seller Smith</div>
														<div class="position">Web developer</div>
														<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
															quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
															nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
															mauris.
														</p>
													</div>
													<div class="item">
														<div class="name">Peter Capidal</div>
														<div class="position">Front-end Developer</div>
														<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
															quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
															nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
															mauris. Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
															lorem quis bibendum auctor, nisi elit conse quat ipsum
														</p>
													</div>
													<div class="item">
														<div class="name">David James</div>
														<div class="position">Developer</div>
														<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
															quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
															nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
															mauris.Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
															lorem quis bibendum auctor, nisi elit conse quat ipsum
														</p>
													</div>
												</div>
												<div class="social-content">
													<div class="social">
														<ul class="list-inline mb-0 justify-content-end">
															<li class="list-inline-item mb-0">
																<a href="#" target="_blank">
																	<i class="fa fa-facebook"></i>
																</a>
															</li>
															<li class="list-inline-item mb-0">
																<a href="#" target="_blank">
																	<i class="fa fa-twitter"></i>
																</a>
															</li>
															<li class="list-inline-item mb-0">
																<a href="#" target="_blank">
																	<i class="fa fa-google"></i>
																</a>
															</li>
															<li class="list-inline-item mb-0">
																<a href="#" target="_blank">
																	<i class="fa fa-instagram"></i>
																</a>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}